### ISSUE TITLE
Code in repo is still at 1.0.0 while latest release is 1.1.4

### ISSUE THREAD

**Issue by antermin** [ProtonVPN/local-agent-rs#5]
>  We are happy to answer your questions about the code or discuss technical ideas. 
 
Please complete the following checklist (by adding [x]):
- [x] I have searched open and closed issues for duplicates
- [x] This isn't a feature request
- [x] This is not a report about my app not working as expected

----------------------------------------

Related: #3

https://github.com/ProtonVPN/local-agent-rs/blob/master/python-proton-vpn-local-agent/debian/changelog indicates that the code in this repo may be outdated, since the changelog contains entry for 1.0.0 but not 1.1.4.

**Comment by calexandru2018** [comment]
Hey @antermin , we'll fix this thank you.

**Comment by jllaneras** [comment]
Hi @antermin, this is fixed now. The default branch is now `stable` instead of `master`.
